name: flutter_code_generation
description: Examples of Flutter Code Generation.
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  # Internationalization support.
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  lint: ^1.10.0
  rive: ^0.9.1

dev_dependencies:
  build_runner: ^2.2.1
  flutter_gen_runner: ^5.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.5.0

flutter_gen:
  output: lib/assets/gen # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  null_safety: true # Optional (default: true)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: ColorName

  assets:
    enabled: true
    outputs:
      class_name: Assets

    # Assets.imagesDash
    # style: camel-case

    # Assets.images_dash
    # style: snake-case

    # Assets.images.dash (default style)
    # style: dot-delimiter

  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter:
  uses-material-design: true
  # Adds code generation (synthetic package) support
  generate: true
  assets:
    - assets/color/
    - assets/flare/
    - assets/images/
    - assets/images/icons/
    - assets/json/
    - assets/rive/
  fonts:
    - family: Fuggles
      fonts:
        - asset: assets/fonts/Fuggles-Regular.ttf
