name: flutter_code_generation
description: Examples of Flutter Code Generation.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flare_flutter: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.2
  intl: ^0.17.0
  lint: ^1.5.3

dev_dependencies:
  build_runner: ^2.0.6
  flutter_gen_runner: ^3.1.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.4

flutter_gen:
  output: lib/assets/gen # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  null_safety: true # Optional (default: true)

  integrations:
    flutter_svg: true
    flare_flutter: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

  assets:
    enabled: true
    # Assets.imagesDash
    # style: camel-case

    # Assets.images_dash
    # style: snake-case

    # Assets.images.dash (default style)
    # style: dot-delimiter

  fonts:
    enabled: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/color/
    - assets/flare/
    - assets/images/
    - assets/images/icons/
    - assets/json/
  fonts:
    - family: Fuggles
      fonts:
        - asset: assets/fonts/Fuggles-Regular.ttf
